apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  name: helloservice-primary
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 9000
  selector:
    app: helloservice-primary
  type: ClusterIP
status:
  loadBalancer: {}
